### ISSUE TITLE
ImportError: cannot import name JSONDecodeError

### ISSUE THREAD

**Issue by ZL1LAC** [fooof-tools/fooof#185]
Never seen this error before!

```
pi@raspberrypi:~/radiosonde_auto_rx/auto_rx $ python auto_rx.py
Traceback (most recent call last):
  File "auto_rx.py", line 31, in <module>
    from autorx.web import start_flask, stop_flask, flask_emit_event, WebHandler, WebExporter
  File "/home/pi/radiosonde_auto_rx/auto_rx/autorx/web.py", line 23, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 21, in <module>
    import socketio
  File "/usr/local/lib/python2.7/dist-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/usr/local/lib/python2.7/dist-packages/socketio/client.py", line 7, in <module>
    import engineio
  File "/usr/local/lib/python2.7/dist-packages/engineio/__init__.py", line 3, in <module>
    from .client import Client
  File "/usr/local/lib/python2.7/dist-packages/engineio/client.py", line 2, in <module>
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
```

**Comment by ZL1LAC** [comment]
uh ok, sorry wrong git repo....
